CREATE TABLE LIST_SEARCH_DB as
SELECT 

LIST_ROMS.NAMEROM,
LIST_ROMS.CONSOLE,

LIST_ROMS.NAMEROM || ' : '  || LIST_GAMES_META_XML.DES as SEARCHTEXT,

LIST_ROMS.PATHFILE as COLLECTIONPATHFILE

from LIST_ROMS, LIST_GAMES_META_XML

where LIST_ROMS.FILE = substr(LIST_GAMES_META_XML.PATH,3)